// Copies the compiled ABIs into the Next.js app (../lib/abi/*.ts) as
// `as const` arrays so viem/wagmi can infer argument and return types.
// The app can't import from contracts/ (excluded in its tsconfig), so this
// is the only bridge between the two toolchains. Re-run after changing any
// Solidity file:
//
//   node ./node_modules/hardhat/internal/cli/cli.js compile
//   node ./scripts/export-abis.js
const fs = require("fs");
const path = require("path");

const CONTRACTS = [
  ["EquityEscrowFactory", "equityEscrowFactoryAbi"],
  ["EquityEscrow", "equityEscrowAbi"],
  ["EquityToken", "equityTokenAbi"],
];

const outDir = path.resolve(__dirname, "../../lib/abi");
fs.mkdirSync(outDir, { recursive: true });

const indexLines = [];

for (const [contract, exportName] of CONTRACTS) {
  const artifactPath = path.resolve(
    __dirname,
    `../artifacts/contracts/${contract}.sol/${contract}.json`,
  );
  const { abi } = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const fileName = `${contract}.ts`;

  fs.writeFileSync(
    path.join(outDir, fileName),
    `// Generated by contracts/scripts/export-abis.js — do not edit by hand.\n` +
      `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  indexLines.push(`export { ${exportName} } from "./${contract}";`);
  console.log(`wrote lib/abi/${fileName} (${abi.length} entries)`);
}

fs.writeFileSync(path.join(outDir, "index.ts"), indexLines.join("\n") + "\n");
